# This workflow will build a Java project with Maven, and the Open-BPMN Docker image
# containing the node.js client part based on Theia Platform 

name: Build and create Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Building Open-BPMN Server with Maven
      run: mvn -B package --file pom.xml

    - name: Building Docker image
      run: docker build . --file Dockerfile --tag imixs/open-bpmn:$(date +%s)
    